name: dictionary
description: A Dictionary APP

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc_test: ^9.0.3
  connectivity_plus: ^2.2.1
  dartz: ^0.10.1
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  font_awesome_flutter: ^10.0.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  http: ^0.13.4
  just_audio: ^0.9.20
  mockito: ^5.1.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dictionary.png"